### ISSUE TITLE
Add support for basic authentication

### ISSUE THREAD

**Issue by mbarretta** [vktr/blaze#2]
Many clusters  (hopefully all production ones) are protected by some authentication and authorization. Adding support for `--user` and `--password` would go a long way to expanding the applicability of this tool.

**Comment by vktr** [comment]
I don't have access to an Elasticsearch instance with an X-Pack security license, but I'll see if I can put up a simple Nginx basic auth proxy in front of the instance I have. Seems like it would work the same, at least according to the docs :)

**Comment by mbarretta** [comment]
Reverse proxy is a common approach of adding a lock to the front door: should be good enough for testing basic auth.

I can test to confirm if it works with a secured cluster issued from [Elastic Cloud](https://cloud.elastic.co). Though, you can always register for a free trial for testing purposes too!

**Comment by vktr** [comment]
Should be fixed in 750a9eb2f4bb854deb719e8dc0e3d7ab515c3de7. Documented here: https://github.com/vktr/blaze#authentication
