### ISSUE TITLE
Broken on ES 2.4

### ISSUE THREAD

**Issue by AlexNodex** [vktr/blaze#3]
Hi.

Testing this on ES 2.4 the exporter doesn't export data only mappings.

Issuing the command `blaze --host=http://localhost:18200 --index=test > test.json` returns the following:

```
Slice 00 exited with error: Server returned HTTP status 400
Slice 01 exited with error: Server returned HTTP status 400
Slice 02 exited with error: Server returned HTTP status 400
Slice 03 exited with error: Server returned HTTP status 400
Slice 04 exited with error: Server returned HTTP status 400
```
Where as just dumping the mappings works as expetced (exports the mappings)

**Comment by vktr** [comment]
The sliced scroll feature (which Blaze builds heavily on) was introduced in 5.x, so unfortunately **2.x is unsupported** as of now. I'll see if I can support both regular scroll and sliced scroll in the future.
